runtime: nodejs20  # still valid for Node tools, even though it's static
instance_class: F1  # free tier eligible

# No need for entrypoint; this is a static site
# entrypoint: serve -s dist

env_variables:
  NODE_ENV: "production"
  
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
  # Vite typically places built assets (JS, CSS) into an 'assets' subfolder in 'dist'.
  # This handler serves those files with long caching.
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/(.*)
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000" # Cache for 1 year

  # Handler for other static files directly in the 'dist' root (e.g., favicon.ico, manifest.json, images).
  # Adjust the regex (.*\.(...)) to include all relevant file types you might have.
  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|webmanifest|txt|json|map|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/(.*\.(ico|png|jpg|jpeg|gif|svg|webmanifest|txt|json|map|woff|woff2|ttf|eot))$
    secure: always
    http_headers:
      Cache-Control: "public, max-age=86400" # Cache for 1 day, adjust as needed

  # Redirect all other traffic to index.html (SPA fallback)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      # to ensure users get the latest version of the app.
      Cache-Control: "no-cache, no-store, must-revalidate"
