// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sioksypvbsutxtzbclfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpb2tzeXB2YnN1dHh0emJjbGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTY0NTAsImV4cCI6MjA2MzQ3MjQ1MH0.lQamZZpfqxzFutmkAB8N4Fka-CfGDEiCGCFhP9v5urE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);